### ISSUE TITLE
why don't you use d3.json?

### ISSUE THREAD

**Issue by duhaime** [qwwqwwq/rails_d3_seed#4]
Out of curiosity, why don't you use d3.json() to fetch json in your example? Is there a reason to prefer jQuery's $.ajax()? I ask because I regularly use d3.json(), but would switch if there's a reason to prefer jQuery's json fetch.

**Comment by qwwqwwq** [comment]
Good question.. I would guess that because fetching data for visualization is such a common use case the d3 authors wanted to support it without making users depend on an external library (which would put pressure on them to make sure d3 is compatible with those external libraries). Not all apps will necessarily have jQuery available, and its a lot nicer if you can minimize the number of javascript libraries you depend on.

**Comment by duhaime** [comment]
Thanks @qwwqwwq, I was thinking the same thing! I'll close this thread.
